version: '3.3'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
    backend:
        container_name: backend
        build: ./node
        restart: always
        ports:
            - 4000:80
        depends_on: 
            - mongodb
        volumes:
            - ./node/api:/app/api
            - ./frontend:/client
        links:
            - mongodb